### ISSUE TITLE
Current version crashing Homebridge

### ISSUE THREAD

**Issue by ultrathew** [SynTexDZN/homebridge-syntex-webhooks#5]
I've been happily using this plugin for months, but running the 2.3.3 update today is causing Homebridge to crash with the following errors:

[1/11/2021, 21:59:34] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:82:11)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at SynTexWebHookPlatform.getAccessory (/usr/local/lib/node_modules/homebridge-syntex-webhooks/node_modules/homebridge-syntex-dynamic-platform/main.js:83:34)
    at SynTexWebHookPlatform.loadAccessories (/usr/local/lib/node_modules/homebridge-syntex-webhooks/index.js:248:37)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-syntex-webhooks/index.js:37:10)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:14)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by SynTexDZN** [comment]
Sorry for the delay. I was really busy there days.
Is your problem solved with the newest version of my plugin or is it still present?

**Problem not solved?**
Then could you please share your config that I can figure out what could be wrong with it. It seems like something goes wrong when the accessories were loaded.

~ **SynTex**

**Comment by ultrathew** [comment]
Thanks for following up. I figured it out on my own. I didn't realize you'd changed syntax for the config entry, so my config file still used "mac" and not "id". All is working fine now.

**Comment by SynTexDZN** [comment]
Great to hear!
I hope you enjoy my plugin :)

~ **SynTex**
