### ISSUE TITLE
Plugin is crashing HB

### ISSUE THREAD

**Issue by ttan** [SynTexDZN/homebridge-syntex-webhooks#7]
New installation of the plugin (tried with several configurations, from 0 to full), always gives me:

```
[07/08/2021, 18:43:24] TypeError: Cannot read property 'addPage' of undefined
    at SynTexWebHookPlatform.initWebServer (/usr/lib/node_modules/homebridge-syntex-webhooks/index.js:38:18)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-syntex-webhooks/index.js:30:10)
    at HomebridgeAPI.emit (events.js:412:35)
    at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:173:14)
```

HB crashes and reboots.

**Comment by SynTexDZN** [comment]
Hello @ttan 🤗
to help us understanding your problem could you please send some more information about your installation by showing the `package.json` and `package-lock.json` of the plugin? It's located under `/usr/lib/node_modules/homebridge-syntex-webhooks/`.

~ ***SynTex***

**Comment by ttan** [comment]
Hi @SynTexDZN thanks for the support! This is the file out of a fresh installation. The lock file is not there.

package.json:

```json
{
  "_from": "homebridge-syntex-webhooks@latest",
  "_id": "homebridge-syntex-webhooks@2.3.4",
  "_inBundle": false,
  "_integrity": "sha512-V14KYIF/hbnDols2DbXJTpRA5KrPaXi8RP3KyvTj/VMliD5ZuOYDCgHBOwPxYYdglMqxcNfJU2rVLut6ty+GHQ==",
  "_location": "/homebridge-syntex-webhooks",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "homebridge-syntex-webhooks@latest",
    "name": "homebridge-syntex-webhooks",
    "escapedName": "homebridge-syntex-webhooks",
    "rawSpec": "latest",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/homebridge-syntex-webhooks/-/homebridge-syntex-webhooks-2.3.4.tgz",
  "_shasum": "27544e356a87176683c1894baf20d360a7722c02",
  "_spec": "homebridge-syntex-webhooks@latest",
  "_where": "/usr",
  "author": {
    "name": "SynTexDZN"
  },
  "bugs": {
    "url": "https://github.com/SynTexDZN/homebridge-syntex-webhooks/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "color-convert": "^1.5.0",
    "homebridge-syntex-dynamic-platform": "^1.0.4",
    "json-fs-store": "^1.0.1",
    "request": "^2.88.0"
  },
  "deprecated": false,
  "description": "A webhook plugin for HTTP devices",
  "engines": {
    "homebridge": ">=0.3.0",
    "node": ">=9.11.2"
  },
  "homepage": "https://github.com/SynTexDZN/homebridge-syntex-webhooks#readme",
  "keywords": [
    "syntex",
    "syntex-webhooks",
    "homebridge-plugin",
    "homebridge",
    "plugin",
    "http",
    "webhook",
    "webhooks",
    "homekit",
    "smarthome",
    "siri"
  ],
  "license": "ISC",
  "main": "index.js",
  "name": "homebridge-syntex-webhooks",
  "repository": {
    "type": "git",
    "url": "git://github.com/SynTexDZN/homebridge-syntex-webhooks.git"
  },
  "version": "2.3.4"
}```

**Comment by SynTexDZN** [comment]
It looks like one of our modules refers to this exception. Is this the only error shown in the log files?
Try to update to the latest beta version with `sudo npm install -g homebridge-syntex-webhooks@2.3.5-b25` and if the problem isn't solved please send us your configuration for the plugin located in your `config.json`

~ ***SynTex***

**Comment by ttan** [comment]
Hi @SynTexDZN the beta version hasn't fixed it either.
I've tried again with basic plugin config, without accessory and adding basic ones, up to a more complete like:

```json
 "platform": "SynTexWebHooks",
            "name": "SynTexWebHooks",
            "accessories": [
                {
                    "id": "studio-light",
                    "name": "Studio Light",
                    "services": {
                        "type": "light",
                        "requests": [
                            {
                                "trigger": "on",
                                "method": "GET",
                                "url": "https://endpoint/toggle/bf81e635113af2bazzz/switch_led/true"
                            },
                            {
                                "trigger": "off",
                                "method": "GET",
                                "url": "https://endpoint/toggle/bf81e635113af2baxxx/switch_led/false"
                            }
                        ]
                    }
                }
            ]
```

The result is still the same error as posted above.

**Comment by SynTexDZN** [comment]
Hey @ttan we found out what was wrong there.
The `port` was documented as an optional parameter but was necessary since now.
We published an beta update for the `homebridge-syntex-webhooks` plugin that made the WebServer optional so you just have to install the new version with `sudo npm install -g homebridge-syntex-webhooks@2.3.5-b25`

If you want to control your accessories with HTTP calls for automation or other purpose you have to add the `port` in your `config.json` file.

I hope this will solve your issue :D

~ ***SynTex***
